Session.set("timer", false)
Session.set("eventId", null)
Session.set("createEvent",false)
Session.set("createGoalTemplate",false)
Session.set("mininav","events")
Session.set("users_count",0)
Session.set("events_toggl",false)
Session.set("loginState",false)
Session.set("goalnav","goals")
